<?php
declare(strict_types=1);
require_once __DIR__ . '/participant_summary.php';
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= escape($title) ?> — PPDB</title><link rel="stylesheet" href="<?= escape(assetUrl('app.css')) ?>"><script src="<?= escape(assetUrl('app.js')) ?>" defer></script></head>
<body class="dashboard-page"><a class="skip-link" href="#main">Lewati ke konten</a><div class="portal-topbar"><header class="dashboard-header"><a class="brand" href="/dashboard"><span class="brand-mark" aria-hidden="true">P</span><span>PPDB<span class="brand-caption">LAYANAN PENDIDIKAN</span></span></a><div class="header-actions"><a class="role-tag" href="/account/security">Akun wali</a><form method="post" action="/logout"><input type="hidden" name="csrf" value="<?= escape(csrfToken()) ?>"><button class="button button-outline">Keluar</button></form></div></header><nav class="portal-nav" aria-label="Navigasi pendaftar"><a href="/dashboard">Beranda</a><a href="/admissions">Pendaftaran</a><a href="/applications/notifications"<?= $screen==='notifications' ? ' aria-current="page"' : '' ?>>Notifikasi</a><a href="/privacy">Privasi</a></nav></div>
<main id="main" class="dashboard-main admission-main admin-workspace"><h1><?= escape($title) ?></h1>
<?php if ($notice): ?><div role="status" class="notice"><?= escape($notice) ?></div><?php endif; ?>
<?php if ($errors): ?><div class="error-summary" role="alert" tabindex="-1" data-error-summary><?= escape($errors['form']) ?><?php if (http_response_code()===409): ?><p><a href="<?= escape($path) ?>">Muat ulang formulir</a></p><?php endif; ?></div><?php endif; ?>
<?php if ($screen==='notifications'): ?><p class="lead">Maksimal 50 notifikasi terakhir, khusus pendaftaran akun Anda. Tidak ada email otomatis.</p><?php foreach ($notices as $item): ?><article class="form-card"><span class="status-tag"><?= $item['read_at'] ? 'Dibaca' : 'Belum dibaca' ?></span><p><?= nl2br(escape($item['message'])) ?></p><p><?= escape(admissionDate((int)$item['created_at'],'Asia/Jakarta')) ?></p><a href="/applications/<?= escape($item['application_id']) ?>/corrections" class="button button-outline">Lihat kiriman / koreksi</a><?php if (!$item['read_at']): ?><form method="post" class="action-row"><input type="hidden" name="csrf" value="<?= escape(csrfToken()) ?>"><input type="hidden" name="notice_id" value="<?= escape($item['id']) ?>"><button class="button button-outline">Tandai dibaca</button></form><?php endif; ?></article><?php endforeach; ?><?php if (!$notices): ?><p>Belum ada notifikasi.</p><?php endif; ?>
<?php elseif ($application && $period): $base='/applications/'.$application['id'].'/corrections'; ?>
<p class="lead"><?= escape($application['registration_number'] . ' · ' . $period['school']) ?></p>
<p>Nomor pendaftaran, jalur, profil peserta, aturan dan kiriman awal tetap utuh. Revisi perlu diperiksa ulang, bukan otomatis Valid atau diterima.</p>
<div class="action-row"><a class="button button-outline" href="<?= escape($base) ?>">Revisi terbaru</a><a class="button button-outline" href="<?= escape($base) ?>?revision=0">Kiriman awal</a><?php foreach ($revisions as $item): if (!(int)$item['revision']) continue; ?><a class="button button-outline" href="<?= escape($base) ?>?revision=<?= (int)$item['revision'] ?>">Revisi <?= (int)$item['revision'] ?></a><?php endforeach; ?><a class="button button-outline" href="/applications/<?= escape($application['id']) ?>/receipt">Tanda terima awal</a></div>
<?php if ($request):
    $writable = $request['status']==='open' && time()>=(int)$request['opens_at'] && time()<(int)$request['deadline'] && $config['environment']==='development';
    $fields = admissionData($request['fields_json']); $docReasons = admissionData($request['documents_json']);
?>
<section class="form-card"><h2>Permintaan perbaikan revisi <?= (int)$request['base_revision'] ?></h2><p><?= nl2br(escape($request['note'])) ?></p><p>Mulai: <?= escape(admissionDate((int)$request['opens_at'],$period['timezone'])) ?><br>Tenggat: <?= escape(admissionDate((int)$request['deadline'],$period['timezone'])) ?></p>
<?php if (!$writable): ?><p class="notice"><?= $request['status']==='submitted' ? 'Sudah dikirim ulang; formulir terkunci.' : 'Di luar rentang koreksi atau hanya baca; perubahan tidak dibuka.' ?></p><?php endif; ?>
<?php if ($fields): ?><form method="post" data-draft-form><input type="hidden" name="csrf" value="<?= escape(csrfToken()) ?>"><input type="hidden" name="version" value="<?= (int)$request['version'] ?>"><input type="hidden" name="action" value="save">
<div class="form-grid"><?php foreach ($fields as $key=>$reason): [$label,$max]=admissionFields()[$key]; ?><div class="field"><label for="field-<?= $key ?>"><?= escape($label) ?></label><p class="field-help"><?= nl2br(escape($reason)) ?></p><?php if (in_array($key,['sex','relationship'],true)): $options=$key==='sex' ? ['L'=>'Laki-laki','P'=>'Perempuan'] : ['Ayah'=>'Ayah','Ibu'=>'Ibu','Wali'=>'Wali']; ?><select id="field-<?= $key ?>" name="fields[<?= $key ?>]"<?= !$writable ? ' disabled' : '' ?>><?php foreach ($options as $code=>$text): ?><option value="<?= $code ?>"<?= ($data[$key] ?? '')===$code ? ' selected' : '' ?>><?= $text ?></option><?php endforeach; ?></select><?php else: ?><input id="field-<?= $key ?>" name="fields[<?= $key ?>]" type="<?= $key==='birth_date' ? 'date' : 'text' ?>" maxlength="<?= $max ?>" value="<?= escape($data[$key] ?? '') ?>"<?= !$writable ? ' disabled' : '' ?>><?php endif; ?><?php if (isset($errors[$key])): ?><p class="field-error"><?= escape($errors[$key]) ?></p><?php endif; ?></div><?php endforeach; ?></div>
<?php if ($writable): ?><button class="button button-primary compact-button">Simpan draf koreksi</button><?php endif; ?></form><?php endif; ?>
<?php foreach ($docReasons as $kind=>$reason): ?><article class="document-card"><h3>Ganti berkas <?= escape($kind) ?></h3><p><?= nl2br(escape($reason)) ?></p><?php if (isset($documents[$kind])): ?><a class="text-link" href="/documents/<?= escape($documents[$kind]['id']) ?>?download=1">Lihat berkas saat ini: <?= escape($documents[$kind]['original_name']) ?></a><?php endif; ?><?php if ($writable): ?><form method="post" enctype="multipart/form-data" class="upload-form"><input type="hidden" name="csrf" value="<?= escape(csrfToken()) ?>"><input type="hidden" name="version" value="<?= (int)$request['version'] ?>"><input type="hidden" name="action" value="upload"><input type="hidden" name="kind" value="<?= escape($kind) ?>"><div class="field"><label for="document-<?= escape($kind) ?>">Berkas pengganti PDF/JPG/PNG, maksimal 2 MB</label><input id="document-<?= escape($kind) ?>" type="file" name="document" accept=".pdf,.jpg,.jpeg,.png" required></div><button class="button button-outline">Unggah pengganti</button></form><?php endif; ?></article><?php endforeach; ?>
<?php if ($writable): ?><form method="post" class="operational-decision"><input type="hidden" name="csrf" value="<?= escape(csrfToken()) ?>"><input type="hidden" name="version" value="<?= (int)$request['version'] ?>"><input type="hidden" name="action" value="submit"><label class="checkbox-field"><input type="checkbox" name="declaration" value="1" required> Saya telah menyimpan semua koreksi dan menyatakan revisi benar sesuai ketentuan privasi.</label><p class="field-help">Semua kolom terpilih harus berubah dan semua berkas terpilih harus diganti. Simpan draf sebelum kirim; tidak ada autosave.</p><button class="button button-primary compact-button">Kirim ulang revisi</button></form><?php endif; ?></section>
<?php endif; ?>
<?php if ($revision): ?><section class="form-card"><h2>Data revisi <?= (int)$revision['revision'] ?></h2><?php participantSummary($data); ?><h3>Berkas versi ini</h3><ul><?php foreach ($documents as $doc): ?><li><a href="/documents/<?= escape($doc['id']) ?>?download=1"><?= escape($doc['kind'] . ' · ' . $doc['original_name']) ?></a></li><?php endforeach; ?></ul></section><?php endif; ?>
<section class="form-card"><h2>Riwayat permintaan koreksi</h2><?php if (!$requests): ?><p>Belum ada permintaan koreksi.</p><?php endif; ?><?php foreach ($requests as $item): ?><article class="document-card"><h3><?= $item['status']==='submitted' ? 'Revisi ' . (int)$item['submitted_revision'] . ' dikirim ulang' : (time()>=(int)$item['deadline'] ? 'Tenggat berakhir' : 'Perlu perbaikan') ?></h3><p><?= nl2br(escape($item['note'])) ?></p><p>Tenggat <?= escape(admissionDate((int)$item['deadline'],$period['timezone'])) ?></p><a class="button button-outline" href="<?= escape($base.'/'.$item['id']) ?>">Lihat / perbaiki bagian terpilih</a></article><?php endforeach; ?></section>
<?php $labels=reviewChecklistItems($application,$documents); $statuses=reviewStatuses(); ?>
<section class="form-card"><h2>Riwayat pemeriksaan rinci</h2><p>Catatan panitia, maksimal 50 terakhir.</p><?php foreach ($reviewHistory as $item): ?><details class="requirement-note"><summary>Revisi <?= (int)$item['revision'] ?> · <?= $item['decision'] ? escape(verificationLabel($item['decision'])) : 'Checklist disimpan' ?></summary><p><?= escape(admissionDate((int)$item['created_at'],$period['timezone'])) ?></p><p><?= nl2br(escape($item['note'])) ?></p><ul><?php foreach (admissionData($item['checklist_json']) as $key=>$check): ?><li><?= escape(admissionDisplayText($labels[$key]['label'] ?? $key) . ' · ' . $statuses[$check['status']] . ': ' . $check['note']) ?></li><?php endforeach; ?></ul></details><?php endforeach; ?></section>
<?php endif; ?></main><footer class="dashboard-footer">PPDB · Layanan pendaftar</footer></body></html>
