<?php
declare(strict_types=1);
$checkStatuses = reviewStatuses();
?>
<section class="form-card"><h2>Versi kiriman</h2><p>Ditampilkan: revisi <?= (int)$latestRevision['revision'] ?>. Kiriman awal dan seluruh berkasnya tetap tersimpan. Revisi terbaru: <?= $reviewedRevision ?>.</p>
<div class="action-row"><a href="<?= escape($path) ?>" class="button button-outline">Periksa revisi terbaru</a><a href="<?= escape($path) ?>?revision=0" class="button button-outline">Kiriman awal</a><?php foreach ($revisions as $revision): if (!(int)$revision['revision']) continue; ?><a href="<?= escape($path) ?>?revision=<?= (int)$revision['revision'] ?>" class="button button-outline">Revisi <?= (int)$revision['revision'] ?></a><?php endforeach; ?></div></section>
<section class="form-card"><h2>Permintaan koreksi</h2>
<?php if (!$correctionRequests): ?><p>Belum ada permintaan koreksi terbatas.</p><?php endif; ?>
<?php foreach ($correctionRequests as $request): ?><article class="document-card"><h3><?= $request['status']==='submitted' ? 'Sudah dikirim ulang · revisi ' . (int)$request['submitted_revision'] : ($request['status']==='expired' || time()>=(int)$request['deadline'] ? 'Tenggat berakhir' : 'Menunggu koreksi wali') ?></h3><p><?= nl2br(escape($request['note'])) ?></p><p>Tenggat: <?= escape(admissionDate((int)$request['deadline'],$period['timezone'])) ?></p><ul><?php foreach (admissionData($request['fields_json']) as $key=>$reason): ?><li><?= escape(admissionFields()[$key][0] . ': ' . $reason) ?></li><?php endforeach; ?><?php foreach (admissionData($request['documents_json']) as $kind=>$reason): ?><li>Berkas <?= escape($kind . ': ' . $reason) ?></li><?php endforeach; ?></ul></article><?php endforeach; ?></section>
<?php if ($revisionView === ''): ?>
<form method="post" class="form-card"><h2>Checklist dan keputusan revisi <?= $reviewedRevision ?></h2>
<input type="hidden" name="csrf" value="<?= escape(csrfToken()) ?>"><input type="hidden" name="verification_version" value="<?= $reviewFormVersion ?>">
<p class="field-help">Isi status dan catatan setiap item. Valid memerlukan seluruh item Valid; dokumen opsional yang tidak ada memakai Tidak berlaku. Checklist tersimpan terpisah dari keputusan. Kriteria kelayakan diperiksa manusia sesuai Juknis, bukan skor otomatis.</p>
<?php foreach ($checklistItems as $key=>$item): $value = $checklistValues[$key] ?? []; ?>
<fieldset class="document-card"><legend><?= escape(admissionDisplayText($item['label'])) ?><?= $item['required'] ? ' · Wajib' : ' · Opsional' ?></legend>
<div class="form-grid"><div class="field"><label for="check-<?= escape($key) ?>">Status pemeriksaan</label><select id="check-<?= escape($key) ?>" name="checklist[<?= escape($key) ?>][status]"><?php foreach ($checkStatuses as $code=>$label): ?><option value="<?= $code ?>"<?= ($value['status'] ?? 'pending')===$code ? ' selected' : '' ?>><?= escape($label) ?></option><?php endforeach; ?></select></div>
<div class="field"><label for="check-note-<?= escape($key) ?>">Catatan item (5–2000 karakter jika diperiksa)</label><textarea id="check-note-<?= escape($key) ?>" name="checklist[<?= escape($key) ?>][note]" maxlength="2000" rows="2"><?= escape(is_string($value['note'] ?? null) ? $value['note'] : '') ?></textarea></div></div></fieldset>
<?php endforeach; ?>
<div class="action-row"><button class="button button-outline" name="action" value="save-checklist">Simpan checklist saja</button></div>
<h3>Keputusan verifikasi</h3><p>Status saat ini: <strong><?= escape(verificationLabel($verification['status'] ?? null)) ?></strong></p>
<div class="field"><label for="decision">Hasil pemeriksaan</label><select id="decision" name="decision"><option value="">Pilih keputusan</option><?php foreach (['valid','needs_correction','invalid'] as $status): ?><option value="<?= $status ?>"<?= $decision===$status ? ' selected' : '' ?>><?= escape(verificationLabel($status)) ?></option><?php endforeach; ?></select></div>
<div class="field"><label for="note">Catatan keputusan untuk wali</label><textarea id="note" name="note" maxlength="2000" rows="3"><?= escape($note) ?></textarea></div>
<details class="requirement-note"><summary>Pilih kolom/berkas untuk koreksi terbatas</summary>
<p>Isi alasan hanya pada bagian yang diminta; kosong berarti terkunci. Kriteria atau dokumen terkait harus Perlu perbaikan. Jalur, periode dan aturan tidak dapat diubah. Meminta koreksi hanya selama tahap Perbaikan paket snapshot, tenggat otomatis akhir tahap.</p>
<div class="form-grid"><?php foreach (admissionFields() as $key=>[$label,$maximum]): ?><div class="field"><label for="reason-<?= $key ?>"><?= escape($label) ?> — alasan koreksi</label><input id="reason-<?= $key ?>" name="correction_fields[<?= $key ?>]" maxlength="2000" value="<?= escape(is_string($_POST['correction_fields'][$key] ?? null) ? $_POST['correction_fields'][$key] : '') ?>"></div><?php endforeach; ?></div>
<?php foreach ($pathway['documents'] as $doc): ?><div class="field"><label for="reason-doc-<?= escape($doc['code']) ?>"><?= escape(admissionDisplayText($doc['label'])) ?> — alasan ganti berkas</label><input id="reason-doc-<?= escape($doc['code']) ?>" name="correction_documents[<?= escape($doc['code']) ?>]" maxlength="2000" value="<?= escape(is_string($_POST['correction_documents'][$doc['code']] ?? null) ? $_POST['correction_documents'][$doc['code']] : '') ?>"></div><?php endforeach; ?>
</details>
<p class="field-help">Simpan keputusan biasa tidak membuka data wali. Gunakan Minta koreksi terbatas untuk membuka bagian terpilih; keputusan harus Perlu perbaikan. Selama permintaan masih terbuka, tunggu kiriman wali; jika tenggat berakhir, panitia dapat memutuskan berdasarkan revisi terakhir.</p>
<div class="action-row"><button class="button button-primary compact-button" name="action" value="verify">Simpan keputusan</button><button class="button button-outline" name="action" value="request-correction">Minta koreksi terbatas</button><a href="/admin/applications" class="button button-outline">Kembali</a></div>
</form>
<?php else: ?><p class="notice">Versi arsip hanya baca. Pemeriksaan dilakukan pada revisi terbaru.</p><?php endif; ?>
<section class="form-card"><h2>Riwayat checklist per revisi</h2><p class="field-help">Maksimal 50 perubahan terakhir; catatan pemeriksaan terlihat oleh wali. Riwayat sebelum A-04 tetap pada riwayat verifikasi.</p>
<?php foreach ($reviewHistory as $review): ?><details class="requirement-note"><summary>Revisi <?= (int)$review['revision'] ?> · <?= $review['decision'] ? escape(verificationLabel($review['decision'])) : 'Checklist disimpan' ?> · <?= escape($review['reviewer_name']) ?></summary><p><?= escape(admissionDate((int)$review['created_at'],$period['timezone'])) ?></p><p><?= nl2br(escape($review['note'])) ?></p><ul><?php foreach (admissionData($review['checklist_json']) as $key=>$item): ?><li><?= escape(($checklistItems[$key]['label'] ?? $key) . ' · ' . $checkStatuses[$item['status']] . ': ' . $item['note']) ?></li><?php endforeach; ?></ul></details><?php endforeach; ?></section>
